{"timestamp":"2025-10-27T08:41:34.675119Z","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager","filename":"manager.py","lineno":179}
{"timestamp":"2025-10-27T08:41:34.676401Z","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/batch_data_server_dag.py","logger":"airflow.models.dagbag.DagBag","filename":"dagbag.py","lineno":593}
{"timestamp":"2025-10-27T08:41:34.853261Z","level":"info","event":"Triggering Dag Run.","trigger_dag_id":"batch_process_watcher_dag","logger":"task","filename":"task_runner.py","lineno":1052}
{"timestamp":"2025-10-27T08:41:34.853621Z","level":"error","event":"Top level error","logger":"task","filename":"task_runner.py","lineno":1457,"error_detail":[{"exc_type":"ValidationError","exc_value":"1 validation error for TriggerDagRun\nconf\n  Input should be a valid dictionary [type=dict_type, input_value=\"{'ids': ['book-41', 'boo... 'book-49', 'book-50']}\", input_type=str]\n    For further information visit https://errors.pydantic.dev/2.11/v/dict_type","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1450,"name":"main"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":940,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1054,"name":"_handle_trigger_dag_run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pydantic/main.py","lineno":253,"name":"__init__"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-10-27T08:41:34.863811Z","level":"warning","event":"Process exited abnormally","exit_code":1,"logger":"task"}
